
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from 'sonner'
import SessionProviderWrapper from '@/components/SessionProviderWrapper';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Toaster richColors position="top-right" closeButton />
        <SessionProviderWrapper>
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
